name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        working-directory: ./.code
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true

      #- name: Cache pnpm modules
      #  uses: actions/cache@v4
      #  with:
      #    path: ./.code/mode_modules
      #    key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      #    restore-keys: |
      #      ${{ runner.os }}-


      - name: Install dependencies
        run: pnpm i
      - name: Create pages
        run: pnpm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: page
          path: ./.code/build
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: page
          path: .

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
